#  Replicator.exp
#  LiteCore
#
#  Created by Jens Alfke on 2/17/17.
#  Copyright © 2017 Couchbase. All rights reserved.

_c4repl_new
_c4repl_free
_c4repl_stop
_c4repl_getStatus

_c4socket_registerFactory
_c4socket_opened
_c4socket_closed
_c4socket_completedWrite
_c4socket_received

.objc_class_name_CBLWebSocket
.objc_class_name_CBLHTTPLogic

_C4RegisterSocketFactory

_kC4ReplicatorActivityLevelNames

