//
// SecureRandomize.hh
//
// Copyright 2015-Present Couchbase, Inc.
//
// Use of this software is governed by the Business Source License included
// in the file licenses/BSL-Couchbase.txt.  As of the Change Date specified
// in that file, in accordance with the Business Source License, use of this
// software will be governed by the Apache License, Version 2.0, included in
// the file licenses/APL2.txt.
//

#pragma once
#include "fleece/slice.hh"
#include <cstdint>

namespace litecore {

    /** Fills memory with cryptographically-secure random bytes. */
    void SecureRandomize(fleece::mutable_slice);

    /** The size of a UUID generated by \ref GenerateUUID. */
    static constexpr size_t SizeOfUUID = 16;

    /** Generates a random unique identifier, conforming to RFC 9562 Type 4.
        @param out  UUID is written here. Size must be \ref SizeOfUUID. */
    void GenerateUUID(fleece::mutable_slice out);

    /** Generates a (non-random!) namespaced UUID, conforming to RFC 9562 Type 5.
        @param out  UUID is written here. Size must be \ref SizeOfUUID.
        @param namespaceUUID  The namespace UUID to encode. Size must be \ref SizeOfUUID.
        @param name  The name to encode. Application-defined but must be in a canonical form. */
    void GenerateNamespacedUUID(fleece::mutable_slice out, fleece::slice namespaceUUID, fleece::slice name);

    /** Returns a random integer in the range [0 .. UINT32_MAX].
        @warning  On some platforms this RNG is cryptographically secure, on others less so. */
    uint32_t RandomNumber();

    /** Returns a random integer in the range [0 .. upperBound-1].
        @warning  On some platforms this RNG is cryptographically secure, on others less so. */
    uint32_t RandomNumber(uint32_t upperBound);
}  // namespace litecore
